base_url = "http://staging.treedom.co/api/v1/"
base_url_backoffice = "http://staging.treedom.co/backoffice/api/v1/"

post_users_link = base_url + "users"
get_users_link = base_url + "users"
put_users_link = base_url + "users"
patch_users_interests_link = base_url + "users/interests"
post_institutions_link = base_url_backoffice + "institutions"
put_institutions_link = base_url_backoffice + "institutions"
get_institutions_link = base_url_backoffice + "institutions"
put_institutions_verify_link = base_url_backoffice + "institutions/verify"
get_institutions_schools_link = base_url_backoffice + "institutions/schools"
post_events_link = base_url_backoffice + "events"
get_refbooks_link = base_url_backoffice + "refbooks"
login_link = "http://staging.treedom.co/"
post_auth = base_url + "auth/login"